var skills = [];
skills[0] = "Problem Solving";
skills[1] = "Programming";
skills.push("js");
// skills = ["js","ts"];
console.log(skills);
var names = ["ajay", "vighnesh", 7];
console.log(names);
var courses;
courses = ["c", "c++"];
courses.push('java');
console.log("courses", courses);
var course = courses[0];
console.log('course', course);
var series = [1, 2, 3, 4, 5];
console.log('length_of_series', series.length);
var num = [1, 2, 3];
var double_num = num.map(function (e) { return e * 2; });
console.log(double_num);
var scores = ['Programming', 5, 'Software Design', 4];
console.log('scores', scores);
var scores1;
scores1 = ["jjjj", 2, 'adcch', 8];
console.log('scores1', scores1);
